### ISSUE TITLE
新規投稿時のテンプレートが動作しない。

### ISSUE THREAD

**Issue by howdy39** [howdy39/q-accelerator#175]
**概要**

新規投稿時のテンプレートが動作しない。

関連
[Qiita > UI > 下書き保存後、下書きを編集しようとすると「Qiitaに投稿」になる。](http://qiita.com/7of9/items/40c2cd9827143734ebd2)

**環境**

- **Q Accelerator Version:1.3.2**
- **Chrome Version: 57.0.2987.98 (64-bit)**

**エラーメッセージ**

```
Q Accelerator | Cannot read property 'value' of null | TypeError: Cannot read property 'value' of null
    at DraftsNewDomHandler.getDraftBody (chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/drafts-new-content.js:3570:41)
    at DefaultBodyContent.setDraftBody (chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/drafts-new-content.js:3473:19)
    at DefaultBodyContent.runByDefaultBody (chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/drafts-new-content.js:3454:12)
    at chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/drafts-new-content.js:3622:42
    at chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/drafts-new-content.js:228:9
    at Object.callback (chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/drafts-new-content.js:871:9)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)
```

**Comment by howdy39** [comment]
クラス名とかそれなりに変わってるので、たぶん仕様変更。

ボタンの件はQiita側のバグ。
切り戻しされると面倒なので２〜３日様子見します。

**Comment by yasokada** [comment]
Qiitaからは特にアナウンスがありませんね。
作業中なのかどうか。
予定のアナウンスがあれば、Qiita APIを使うユーザもそれぞれ対応ができると思うのですが。。。

**Comment by howdy39** [comment]
切り戻しされる気配がないので現状の仕様を正とみなしました。
v1.3.3で対応済みです。

**Comment by yasokada** [comment]
ご対応ありがとうございました。

これでまた下書きが使えるようになり、便利になります。
