### ISSUE TITLE
ベータ版表示の場合諸々の機能が動作していない

### ISSUE THREAD

**Issue by nawada** [howdy39/q-accelerator#181]
\# 動作対象外かもしれませんが…

**概要**

私が確認した範囲では以下の点が確認できました。

- 「いいね」時に「ストック」されない
- コードスニペットに表示される行番号とコピーボタンがおかしい

**環境**

- **Q Accelerator Version:** `1.3.4`
- **Chrome Version:** `62.0.3202.94 `

**エラーメッセージ**

##### ページオープン時

```
Q Accelerator | Cannot read property 'textContent' of null | TypeError: Cannot read property 'textContent' of null
    at ArticleDomHandler.getTitle (chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:6906:40)
    at SaveHistoryContent.run (chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:19135:27)
    at chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:20276:35
    at chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:4535:9
    at Object.callback (chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:5178:9)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)

Q Accelerator | Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'. | TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at AutoLikeContent.run (chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:18860:10)
    at chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:20284:39
    at chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:4535:9
    at Object.callback (chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:5178:9)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)

Q Accelerator | Cannot read property 'getAttribute' of null | TypeError: Cannot read property 'getAttribute' of null
    at ArticleDomHandler.showArticleUpdateTime (chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:6999:17)
    at ShowArticlesUpToTimeContent.run (chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:19180:15)
    at chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:20292:51
    at chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:4535:9
    at Object.callback (chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:5178:9)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)

chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:4581 Q Accelerator | Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'. | TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at ShowStockCountsContent.run (chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:19337:10)
    at chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:20300:46
    at chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:4535:9
    at Object.callback (chrome-extension://mheleidccioamimekojienbdfclcbaan/content_scripts/article-content.js:5178:9)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

##### 行番号とコピーボタン

<img width="458" alt="2017-11-28 13 29 30" src="https://user-images.githubusercontent.com/3747312/33302546-3bdb0284-d440-11e7-9c60-966a1c62639d.png">

**Comment by howdy39** [comment]
@nawada 
報告ありがとうございます。
ひとまずオプション画面からコピーと行番号の設定をオフにして貰えれば、と思います。

ベータ版が私に降ってきていないため画面の確認もできなかったので助かります。

**Comment by kelaductor** [comment]
今日から本番で有効になってまさにこの状況になりました＞＜

**Comment by howdy39** [comment]
@nawada @kelaductor 
>コードスニペットに表示される行番号とコピーボタンがおかしい

とりあえずレイアウト崩れるのは看過できないのでこっちは対応しました。(v1.3.5)
そのうち反映されると思います。

**Comment by nawada** [comment]
1.3.5が適用され、行番号とコピーボタンの表示が直りました！
ありがとうございます。

**Comment by howdy39** [comment]
v1.3.5で次の不具合を修正しました。

* ストック数を表示
* 記事の更新時間を表示
* 自動いいね/自動ストック
